{{- if .Values.enabled }}
# demo-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-localhost-ingress
  namespace: {{ .Release.Name }}
  annotations:
    # Use the appropriate ingress class annotation for your setup (e.g., nginx, traefik)
    kubernetes.io/ingress.class: "nginx" 
spec:
  ingressClassName: nginx # Use this field for K8s v1.18+
  rules:
  - host: "localhost.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-service
            port:
              number: 80
{{- end }}
