{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
  namespace: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.password | b64enc }}
{{- end }}
