apiVersion: v1
kind: Service
metadata:
  name: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.port }}
      name: postgres
  selector:
    app: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
