apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
spec:
  serviceName: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.port }}
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "postgres" }} # {{ printf "%s-postgres" .Release.Name }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgresDatabase | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
