{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "spark-master" }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "spark-master" }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: spark-port
    - port: {{ .Values.service.webPort }}
      name: web-port
  selector:
    app: {{ printf "spark-master" }}
{{- end }}