{{- if and .Values.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "jupyter" }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "jupyter" }}
spec:
  ingressClassName: nginx
  rules:
  - host: demo.localtest.me
    http:
      paths:
        - backend:
            service:
              name: http
              port: 
                number: 8081 
          path: {{ .Values.ingress.path }}
          pathType: Prefix
          
{{- end }}
