{{- if and .Values.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "jupyter" }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "jupyter" }}
  annotations:
    # If using the default Traefik controller in K3s/Rancher Desktop, no class annotation is strictly needed, 
    # but you can specify it for clarity.
    kubernetes.io/ingress.class: traefik 
spec:
  ingressClassName: traefik # {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - backend:
            service:
              name: {{ .Values.name }}
              port: 
                number: {{ .Values.ingress.port }}
          path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          
{{- end }}
