{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ printf "jupyter" }}
spec:
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ printf "jupyter" }}
  template:
    metadata:
      labels:
        app: {{ printf "jupyter" }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
          - name: JUPYTER_PORT
            value: "8081"
          ports:
            - containerPort: {{ .Values.port }}
              name: http
{{- end}}