replicaCount: 1
enabled: false
name: jupyter-notebook
image:
  repository: jupyter/pyspark-notebook
  tag: "x86_64-lab-4.0.7"
  pullPolicy: IfNotPresent
ports:
  - port: 8081
    name: http
    # nodePort: 30702
persistence:
  enabled: true
  size: 2Gi
  storageClass: ""
resources: {}
createSecret: true
env:
  - name: JUPYTER_PORT
    value: "8081"
  # - name: JUPYTER_ENABLE_LAB
  #   value: "yes"
  # - name: GRANT_SUDO
  #   value: "yes"
  # - name: JUPYTER_TOKEN
  #   value: "sparkfun"
  # - name: SPARK_MASTER
  #   value: "spark://spark-master:7077"
  # - name: SPARK_HOME
  #   value: "/opt/spark"
  # - name: HADOOP_CONF_DIR
  #   value: "/opt/hadoop/etc/hadoop"
  # - name: PYSPARK_PYTHON
  #   value: "python3"

ingress:
  enabled: true
  # ingress class name (optional)
  className: ""
  host: jupyter.local
  path: /
  pathType: ImplementationSpecific
  annotations: {}
  tls: []